version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
          -  mypos-mysql
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Dockerfile
    depends_on:
          -  mypos-mysql
  mypos-mysql:
      image: mysql:5.7.35
      environment:
        MYSQL_DATABASE: account
        MYSQL_ROOT_PASSWORD: root123
      volumes:
        - ./mysql-data:/var/lib/mysql
        - ./mysql-scripts/init.sql:/docker-entrypoint-initdb.d/1.sql
      restart: always
      ports:
        - "33061:3306"
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  mysql-data:
  