version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:80"

